<?php 
/**
 * @file
 *
 * 	String constants
 */
DEFINE('IPROJECTWEB_About', "About");
DEFINE('IPROJECTWEB_ActualDeadline', "Actual deadline");
DEFINE('IPROJECTWEB_ActualEffort', "Actual effort");
DEFINE('IPROJECTWEB_Add', "Add");
DEFINE('IPROJECTWEB_Administration', "Administration");
DEFINE('IPROJECTWEB_AdminPartApplicationWidth', "Admin part application width (px)");
DEFINE('IPROJECTWEB_AdminPartDefaultStyle', "Admin part style");
DEFINE('IPROJECTWEB_ApplicationSetting', "Application setting");
DEFINE('IPROJECTWEB_ApplicationSettings', "Application settings");
DEFINE('IPROJECTWEB_ApplicationWidth', "Application width (px)");
DEFINE('IPROJECTWEB_Apply', "Apply");
DEFINE('IPROJECTWEB_AppSettingsProphtmleditorProp', "App settings prophtmleditor prop");
DEFINE('IPROJECTWEB_AppSettingsStyleProp', "App settings style prop");
DEFINE('IPROJECTWEB_AvailableProjectRoles', "Available project roles");
DEFINE('IPROJECTWEB_AvailableProjects', "Available projects");
DEFINE('IPROJECTWEB_AvailableRisks', "Available risks");
DEFINE('IPROJECTWEB_AvailableTasks', "Available tasks");
DEFINE('IPROJECTWEB_Back', "Back");
DEFINE('IPROJECTWEB_Birthday', "Birthday");
DEFINE('IPROJECTWEB_Cell', "Mobile");
DEFINE('IPROJECTWEB_ClickToAddToTheTemplate', "Click to add to the template");
DEFINE('IPROJECTWEB_Close', "Close");
DEFINE('IPROJECTWEB_CloseFilter', "Close filter");
DEFINE('IPROJECTWEB_CMSId', "Site user");
DEFINE('IPROJECTWEB_Comment', "Comment");
DEFINE('IPROJECTWEB_ContactData', "Contact data");
DEFINE('IPROJECTWEB_Contacts', "Contacts");
DEFINE('IPROJECTWEB_CouldNotConnectToDB', "Could not connect to the database");
DEFINE('IPROJECTWEB_Count', "Count");
DEFINE('IPROJECTWEB_Date', "Date");
DEFINE('IPROJECTWEB_DateFormat', "Y-m-d");
DEFINE('IPROJECTWEB_DateFormatCalendar', "%Y-%m-%d");
DEFINE('IPROJECTWEB_DateTimeFormat', "Y-m-d H:i");
DEFINE('IPROJECTWEB_DBConnectionError', "Database connection error");
DEFINE('IPROJECTWEB_Deadline', "Deadline");
DEFINE('IPROJECTWEB_DefaultStyle', "Front-end style");
DEFINE('IPROJECTWEB_Delete', "Delete");
DEFINE('IPROJECTWEB_Description', "Title");
DEFINE('IPROJECTWEB_Docfield', "Docfield");
DEFINE('IPROJECTWEB_Docid', "Docid");
DEFINE('IPROJECTWEB_Doctype', "Doctype");
DEFINE('IPROJECTWEB_Download', "Download");
DEFINE('IPROJECTWEB_Edit', "Edit");
DEFINE('IPROJECTWEB_Effort', "Effort");
DEFINE('IPROJECTWEB_email', "Email");
DEFINE('IPROJECTWEB_email2', "email 2");
DEFINE('IPROJECTWEB_EmailSettings', "Email settings");
DEFINE('IPROJECTWEB_EmailTemplate', "Email template");
DEFINE('IPROJECTWEB_Empty', "");
DEFINE('IPROJECTWEB_File', "File");
DEFINE('IPROJECTWEB_FileFolder', "File folder");
DEFINE('IPROJECTWEB_FileNotFoundInDownloads', "File not found in downloads");
DEFINE('IPROJECTWEB_Files', "Files");
DEFINE('IPROJECTWEB_Filter', "Filter");
DEFINE('IPROJECTWEB_FinishDate', "Finish date");
DEFINE('IPROJECTWEB_FirstName', "First name");
DEFINE('IPROJECTWEB_GeneralInfo', "General info");
DEFINE('IPROJECTWEB_GeneralSettings', "General");
DEFINE('IPROJECTWEB_Help', "Help");
DEFINE('IPROJECTWEB_History', "History");
DEFINE('IPROJECTWEB_HtmlFormat', "HTML Format");
DEFINE('IPROJECTWEB_id', "id");
DEFINE('IPROJECTWEB_idid', "&nbsp;");
DEFINE('IPROJECTWEB_Impact', "Impact");
DEFINE('IPROJECTWEB_ImpossibleToPerformOperation', "Impossible to perform operation");
DEFINE('IPROJECTWEB_iProject', "iProject Web.");
DEFINE('IPROJECTWEB_iProjects', "iProjects");
DEFINE('IPROJECTWEB_ItwillDeleteRecordsAreYouSure', "Selected items will be deleted. Do you wish to continue?");
DEFINE('IPROJECTWEB_KnowlegeBase', "Knowlege base");
DEFINE('IPROJECTWEB_LastName', "Last name");
DEFINE('IPROJECTWEB_License', "Copyright: Georgiy Vasylyev, 2008-2012 | http://wp-pal.com
-----------------------------------------------------------
 
iProject Web
 
For details and latest version and other products, please visit us at http://wp-pal.com;

This product is distributed under terms of the GNU General Public License (http://www.gnu.org/licenses/gpl-2.0.txt).
 
Please contact us at support@wp-pal.com if you encounter any issues. Anyone is welcome.
 
Thank you for using iProject Web.
");
DEFINE('IPROJECTWEB_ListPosition', "List order");
DEFINE('IPROJECTWEB_MailingLists', "Mailing lists");
DEFINE('IPROJECTWEB_Manager', "Manager");
DEFINE('IPROJECTWEB_Members', "Members");
DEFINE('IPROJECTWEB_MitigationPlan', "Mitigation plan");
DEFINE('IPROJECTWEB_MitigationPlanInfo', "Mitigation plan");
DEFINE('IPROJECTWEB_MitigationStrategy', "Strategy");
DEFINE('IPROJECTWEB_More', "More");
DEFINE('IPROJECTWEB_Name', "Name");
DEFINE('IPROJECTWEB_New', "New");
DEFINE('IPROJECTWEB_NewApplicationSettings', "New application setting");
DEFINE('IPROJECTWEB_NewComment', "New comment");
DEFINE('IPROJECTWEB_NewCommentSubject', "New comment subject");
DEFINE('IPROJECTWEB_NewFiles', "New file");
DEFINE('IPROJECTWEB_NewPriorities', "New priority");
DEFINE('IPROJECTWEB_NewProjectField1', "New project field 1");
DEFINE('IPROJECTWEB_NewProjectField2', "New project field 2");
DEFINE('IPROJECTWEB_NewProjectFiles', "New project file");
DEFINE('IPROJECTWEB_NewProjectRoles', "New project role");
DEFINE('IPROJECTWEB_NewProjects', "New project");
DEFINE('IPROJECTWEB_NewProjectStatuses', "New project status");
DEFINE('IPROJECTWEB_NewRiskImpacts', "New risk impact");
DEFINE('IPROJECTWEB_NewRiskProbabilities', "New risk probability");
DEFINE('IPROJECTWEB_NewRisks', "New risk");
DEFINE('IPROJECTWEB_NewRiskStatuses', "New risk status");
DEFINE('IPROJECTWEB_NewRiskStrategies', "New risk strategy");
DEFINE('IPROJECTWEB_NewRiskTypes', "New risk type");
DEFINE('IPROJECTWEB_NewRoles', "New role");
DEFINE('IPROJECTWEB_NewTaskFiles', "New task file");
DEFINE('IPROJECTWEB_NewTasks', "New task");
DEFINE('IPROJECTWEB_NewTaskStatuses', "New task status");
DEFINE('IPROJECTWEB_NewTaskTypes', "New task type");
DEFINE('IPROJECTWEB_NewUserField1', "New user field 1");
DEFINE('IPROJECTWEB_NewUserField2', "New user field 2");
DEFINE('IPROJECTWEB_NewUsers', "New user");
DEFINE('IPROJECTWEB_NewUserTypes', "New user type");
DEFINE('IPROJECTWEB_NoRecordsSelected', "No records selected");
DEFINE('IPROJECTWEB_NoResults', "No results");
DEFINE('IPROJECTWEB_Notes', "Notes");
DEFINE('IPROJECTWEB_NotificationSubject', "Notification subject");
DEFINE('IPROJECTWEB_NotifyOnNewComment', "Notify on new comment");
DEFINE('IPROJECTWEB_NotifyOnStatusChange', "Notify on status change");
DEFINE('IPROJECTWEB_NotLoggedInText', "Not logged in text");
DEFINE('IPROJECTWEB_ObjectOwner', "Owner");
DEFINE('IPROJECTWEB_Of', "of");
DEFINE('IPROJECTWEB_OK', "OK");
DEFINE('IPROJECTWEB_Phone', "Phone");
DEFINE('IPROJECTWEB_Photo', "Photo");
DEFINE('IPROJECTWEB_Photos', "Photos");
DEFINE('IPROJECTWEB_PlannedDeadline', "Planned deadline");
DEFINE('IPROJECTWEB_PlannedEffort', "Planned effort");
DEFINE('IPROJECTWEB_Priorities', "Priorities");
DEFINE('IPROJECTWEB_Priority', "Priority");
DEFINE('IPROJECTWEB_Probability', "Probability");
DEFINE('IPROJECTWEB_Project', "Project");
DEFINE('IPROJECTWEB_ProjectDescription', "About");
DEFINE('IPROJECTWEB_ProjectEmailSettings', "Project email");
DEFINE('IPROJECTWEB_ProjectField1', "Project field 1");
DEFINE('IPROJECTWEB_ProjectField2', "Project field 2");
DEFINE('IPROJECTWEB_ProjectField3', "Project field 3");
DEFINE('IPROJECTWEB_ProjectField4', "Project field 4");
DEFINE('IPROJECTWEB_ProjectFile', "Project file");
DEFINE('IPROJECTWEB_ProjectFiles', "Project files");
DEFINE('IPROJECTWEB_ProjectMailingList', "Mailing list");
DEFINE('IPROJECTWEB_ProjectMailingLists', "Project mailing lists");
DEFINE('IPROJECTWEB_ProjectRole', "Project role");
DEFINE('IPROJECTWEB_ProjectRoles', "Project roles");
DEFINE('IPROJECTWEB_Projects', "Projects");
DEFINE('IPROJECTWEB_ProjectSettings', "Project");
DEFINE('IPROJECTWEB_ProjectStatus', "Project status");
DEFINE('IPROJECTWEB_ProjectStatuses', "Project statuses");
DEFINE('IPROJECTWEB_ProjectTeam', "Team");
DEFINE('IPROJECTWEB_ProjectTeamMember', "Member of ...");
DEFINE('IPROJECTWEB_ProjectTeams', "Project teams");
DEFINE('IPROJECTWEB_Protected', "Prot.");
DEFINE('IPROJECTWEB_ReportsFooterProp', "Reports footer prop");
DEFINE('IPROJECTWEB_ReportsHeaderProp', "Reports header prop");
DEFINE('IPROJECTWEB_Responsible', "Responsible");
DEFINE('IPROJECTWEB_Risk', "Risk");
DEFINE('IPROJECTWEB_RiskDescription', "Risk description");
DEFINE('IPROJECTWEB_RiskEmailSettings', "Risk email");
DEFINE('IPROJECTWEB_RiskImpact', "Risk impact");
DEFINE('IPROJECTWEB_RiskImpacts', "Risk impacts");
DEFINE('IPROJECTWEB_RiskMailingList', "Mailing list");
DEFINE('IPROJECTWEB_RiskMailingLists', "Risk mailing lists");
DEFINE('IPROJECTWEB_RiskProbabilities', "Risk probabilities");
DEFINE('IPROJECTWEB_RiskProbability', "Risk probability");
DEFINE('IPROJECTWEB_Risks', "Risks");
DEFINE('IPROJECTWEB_RiskSettings', "Risk");
DEFINE('IPROJECTWEB_RiskStatus', "Risk status");
DEFINE('IPROJECTWEB_RiskStatuses', "Risk statuses");
DEFINE('IPROJECTWEB_RiskStrategies', "Risk strategies");
DEFINE('IPROJECTWEB_RiskStrategy', "Risk strategy");
DEFINE('IPROJECTWEB_RiskType', "Risk type");
DEFINE('IPROJECTWEB_RiskTypes', "Risk types");
DEFINE('IPROJECTWEB_Role', "Role");
DEFINE('IPROJECTWEB_Roles', "Roles");
DEFINE('IPROJECTWEB_ScrollerBack', "Back");
DEFINE('IPROJECTWEB_ScrollerFirst', "First");
DEFINE('IPROJECTWEB_ScrollerForward', "Next");
DEFINE('IPROJECTWEB_ScrollerLast', "Last");
DEFINE('IPROJECTWEB_ScrollerRows', "Rows");
DEFINE('IPROJECTWEB_Search', "Search");
DEFINE('IPROJECTWEB_SecretWord', "Secret word");
DEFINE('IPROJECTWEB_SendFrom', "Send from");
DEFINE('IPROJECTWEB_SIGN_ANY', "ANY");
DEFINE('IPROJECTWEB_SIGN_BETWEEN', "BTW");
DEFINE('IPROJECTWEB_SIGN_EQUAL', "=");
DEFINE('IPROJECTWEB_SIGN_IN', "IN");
DEFINE('IPROJECTWEB_SIGN_LESS', "<");
DEFINE('IPROJECTWEB_SIGN_LESSOREQUAL', "<=");
DEFINE('IPROJECTWEB_SIGN_LIKE', "LIKE");
DEFINE('IPROJECTWEB_SIGN_MORE', ">");
DEFINE('IPROJECTWEB_SIGN_MOREOREQUAL', ">=");
DEFINE('IPROJECTWEB_SIGN_NOT', "NOT");
DEFINE('IPROJECTWEB_SIGN_NOT_EQUAL', "<>");
DEFINE('IPROJECTWEB_Size', "Size");
DEFINE('IPROJECTWEB_SkypeId', "Skype id");
DEFINE('IPROJECTWEB_StartDate', "Start date");
DEFINE('IPROJECTWEB_Status', "Status");
DEFINE('IPROJECTWEB_StatusChanged', "Status changed");
DEFINE('IPROJECTWEB_StatusChangeSubject', "Status change subject");
DEFINE('IPROJECTWEB_Storagename', "Storagename");
DEFINE('IPROJECTWEB_Submitter', "Submitter");
DEFINE('IPROJECTWEB_Task', "Task");
DEFINE('IPROJECTWEB_TaskEmailSettings', "Task email");
DEFINE('IPROJECTWEB_TaskFile', "Task file");
DEFINE('IPROJECTWEB_TaskFiles', "Task files");
DEFINE('IPROJECTWEB_TaskMailingList', "Mailing list");
DEFINE('IPROJECTWEB_TaskMailingLists', "Task mailing lists");
DEFINE('IPROJECTWEB_Tasks', "Tasks");
DEFINE('IPROJECTWEB_TaskSettings', "Task settings");
DEFINE('IPROJECTWEB_TaskStatus', "Task status");
DEFINE('IPROJECTWEB_TaskStatuses', "Task statuses");
DEFINE('IPROJECTWEB_TaskType', "Type");
DEFINE('IPROJECTWEB_TaskTypes', "Task types");
DEFINE('IPROJECTWEB_thumbPhoto', "Thumbnail");
DEFINE('IPROJECTWEB_TinyMCEConfig', "TinyMCE config");
DEFINE('IPROJECTWEB_TinyMCEDefaultProp', "TinyMCE default prop");
DEFINE('IPROJECTWEB_TinyMCESettings', "Editor");
DEFINE('IPROJECTWEB_Title', "Title");
DEFINE('IPROJECTWEB_Type', "Type");
DEFINE('IPROJECTWEB_Update', "Update");
DEFINE('IPROJECTWEB_Upload', "Upload");
DEFINE('IPROJECTWEB_Uploading', "Uploading");
DEFINE('IPROJECTWEB_User', "User");
DEFINE('IPROJECTWEB_UserField1', "User field 1");
DEFINE('IPROJECTWEB_UserField2', "User field 2");
DEFINE('IPROJECTWEB_UserField3', "User field 3");
DEFINE('IPROJECTWEB_UserField4', "User field 4");
DEFINE('IPROJECTWEB_UserFile', "User file");
DEFINE('IPROJECTWEB_Users', "Users");
DEFINE('IPROJECTWEB_UserSettings', "User settings");
DEFINE('IPROJECTWEB_UserType', "User type");
DEFINE('IPROJECTWEB_UserTypes', "User types");
DEFINE('IPROJECTWEB_UseTinyMCE', "Use TinyMCE");
DEFINE('IPROJECTWEB_ViewScroller', "View scroller");
DEFINE('IPROJECTWEB_Webdir', "Web.");
DEFINE('IPROJECTWEB_YouAreNotLoggedIn', "You are not logged in. Please log in");
